# Generated by Django 2.2.7 on 2019-11-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191130_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.ProductBrand'),
        ),
    ]
